### ISSUE TITLE
Support for Unifi Dream Machine Pro

### ISSUE THREAD

**Issue by Dragonpark** [hjdhjd/homebridge-unifi-protect2#8] opened 2019-11-26 18:34 UTC
I wanted to put this here for those that may be trying to use this with the UDM-Pro as it will not work in most environments. Currently, the API is returning an IPv6 address for the nvr.host property. This means this plugin will not work as-is (though may work if you have setup IPv6 in your network). I could not find an option to disable IPv6 on the controller, so I believe the only way to work around this is if we had a way to override the json response for 'nvr.host'.

Snippet response from api/bootsrap:
```
...
"nvr": {
        "mac": "FCECDAAAAAAA",
        "host": "fe80::aaaa:aaaa:aaaa:aaaa",
        "name": "UDM-Pro",
        "canAutoUpdate": false,
...
```

**Comment by acesarewld** [comment] 2020-02-11 02:55
Hey, it's been some time (and a few updates) later... I upgraded to a Dream Machine Pro - and now I'm unable to make this plugin work. Have there been any updates or progress on this? Thanks!!

**Comment by scoobaspeaz** [comment] 2020-03-09 21:36
I wasn't aware the UDM Pro could do this with the camera. I thought it had to have a cloud key gen 2 in order for it to work. I know the UDM has a gen 2 cloud key built into it but from everything I read it was not compatible with Unifi Protect yet.

**Comment by hfagelnour** [comment] 2020-04-20 02:15
anyway to get this working? pls

**Comment by hjdhjd** [comment] 2020-05-10 07:22
Stay tuned...coming shortly.

**Comment by philipsaad** [comment] 2020-05-10 07:29
> I wasn't aware the UDM Pro could do this with the camera. I thought it had to have a cloud key gen 2 in order for it to work. I know the UDM has a gen 2 cloud key built into it but from everything I read it was not compatible with Unifi Protect yet.

The UDM-**Pro** has a bay for a 3.5in hard drive, if you install a drive you can use Protect. The regular UDM doesn't have this feature because it does not have a hard drive nor the ability to have one, but it has a built in AP whereas the Pro does not.

Hope that clears it up.

**Comment by hjdhjd** [comment] 2020-05-10 07:33
That’s correct. I don’t have a UDM-Pro to test on...but given that support for Protect on UDM-Pro’s has stabilized somewhat, I’m going to tackle support for it. I’m a bit puzzled why things seem to work differently for Protect on a UDM-Pro versus a CK2+, but hey I’m just trying to get something stable working so we don’t end up with a finicky HomeKit plugin at the end of all this. :)

**Comment by hjdhjd** [comment] 2020-05-18 16:58
All - I've updated the plugin with support for UDM-Pro and other UniFiOS devices. Please give this a go and confirm things work as they should. I don't have a UDM-Pro to test on, but things should work properly. Thanks!

**Comment by coice** [comment] 2020-05-19 04:23
@hjdhjd I can confirm this works on UDM-Pro. I needed to remove the port from the controller URL. Also, I created a local account under UDM Users and used that for the login. Great job on this!

**Comment by hjdhjd** [comment] 2020-05-19 05:56
Thanks @coice - can you share what you were using for your url setting before and after? Including the port shouldn't make a difference, and I'd like to debug it a bit.

**Comment by coice** [comment] 2020-05-19 16:11
@hjdhjd It does **not** work if you include the port in the URL, I just tried again with the port included. It throws an api/auth exception:

`(node:17505) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot 
POST /api/auth</pre>\n</body>\n</html>\n"
    at new StatusCodeError (/usr/lib/node_modules/homebridge-unifi-protect2/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/lib/node_modules/homebridge-unifi-protect2/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-unifi-protect2/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/lib/node_modules/homebridge-unifi-protect2/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-unifi-protect2/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-unifi-protect2/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:17505) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise
 which was not handled with .catch(). (rejection id: 1)
`
 Also SSL (https) is required. This is the config I am currently using:

`"platforms": [
  {
    "platform": "Camera-UniFi-Protect",
    "name": "UniFi Protect",

    "controllers": [
      {
        "url": "https://192.168.1.1/",
        "username": "xxx",
        "password": "xxx"
      }
    ]
  }
]`

**Comment by hjdhjd** [comment] 2020-05-19 22:22
Updated documentation to reflect the configuration differences between UCK Gen2+ and UnifiOS devices. @coice - can you update to the latest and verify everything works? It should - you should *not* specify a port in the URL string on UnifiOS. Thanks!

**Comment by coice** [comment] 2020-05-20 01:42
@hjdhjd I updated to 1.2.14 and can confirm it is working correctly. 👍

**Comment by hjdhjd** [comment] 2020-05-20 02:15
Terrific! Closing this one out.

**Closed by hjdhjd** 2020-05-20 02:15 UTC
