### ISSUE TITLE
Fail to "Live" stream over LTE or out of LAN

### ISSUE THREAD

**Issue by fpuigb** [hjdhjd/homebridge-unifi-protect2#56] opened 2020-08-29 03:57 UTC
I was not able to stream "Live" video from any camera over LTE or outside the LAN. 

After saw another reported issue thread, I decided to try the (Enable.StreamOnly.Low). After add this "feature" I'm able to stream from LTE. 

I was getting (ffmpeg exited with code: 0 and signal: null (Error). Now from 5 tries 1 fail but could be related to the Home App out of sync. 

My HB runs in a Dell server running VMware and an all Ubiquiti network; UDMP, switches, APs and the NVR is the UNVR4. For testing purpose, I setup a RPi but the issue continued. The HB reside in the same VLAN as the UNVR. 

At this point I don't think the issue is FW because the request is getting from the WAN to the HB and there is no FW rule to isolate the VLAN from the WAN. 

I'm not sure why I have to use (Enable.StreamOnly.Low) to get it working. 

Edit: I forgot to mention that over LAN everything works correctly with very little delay...

**Comment by fpuigb** [comment] 2020-08-29 04:00
@hjdhjd - to better understand and narrow my TS. The (Enable.StreamOnly.Low) basically restrict the bandwidth between the cameras / UNVR and the HB?

**Comment by hjdhjd** [comment] 2020-08-29 04:01
Thanks for the issue and the detailed information. First...you've got it working, so that's a win!

Now...let's figure out why it's not working by default, shall we?

First things first:

1. Do things work over the local network?
2. What exactly is the network setup that you have here? Doesn't sound like it's directly the issue, but it helps to understand all the pieces.
3. What are the cameras in question?
4. Do all the cameras have this issue?
5. Were prior releases of this plugin working well and this is a new issue, or are you new to homebridge-unifi-protect2?

**Comment by hjdhjd** [comment] 2020-08-29 04:03
There is extensive documentation for this plugin: https://github.com/hjdhjd/homebridge-unifi-protect2/tree/master/docs

Including feature options:

https://github.com/hjdhjd/homebridge-unifi-protect2/blob/master/docs/FeatureOptions.md

**Comment by fpuigb** [comment] 2020-08-29 04:08
**1. Do things work over the local network?**

- Yes, no problem over LAN. 

 **2. What exactly is the network setup that you have here? Doesn't sound like it's directly the issue, but it helps to understand all the pieces.**

- UDMP <-> Ubiquiti 24 ports SW <-> UNVR4 <-> Dell server running VMware and HB in a dedicated VLAN. The VM reside in the same VLAN as the UNVR. 

**3. What are the cameras in question?**

- I have 12 cameras G3-Flex + 1 doorbell. 

**4. Do all the cameras have this issue?**

- All of them do the same thing. 

**5. Were prior releases of this plugin working well and this is a new issue, or are you new to homebridge-unifi-protect2?**

- I have been testing since v 3.1.0

**Comment by hjdhjd** [comment] 2020-08-29 04:13
On 2...what's the setup of Homebridge on VMware on your Dell? Specifically, how many NICs does the Dell have, and how many are configured in the VM that Homebridge runs in?

On 5...you left out where this was an issue in prior releases or a new one.

**Comment by fpuigb** [comment] 2020-08-29 04:14
> There is extensive documentation for this plugin: https://github.com/hjdhjd/homebridge-unifi-protect2/tree/master/docs
> 
> Including feature options:
> 
> https://github.com/hjdhjd/homebridge-unifi-protect2/blob/master/docs/FeatureOptions.md

Yes, I have been reading all the documentation from the beginning of your development and its awesome. Very well documented. But, I still not understanding this;

**Only allow the stream of quality Quality to be used in HomeKit. Valid quality settings are Low, Medium, High.**

What I want to understand is, the restriction of quality is between HB and the UNVR or HB and HomeKit App? Sorry for all the questions just trying to understand what's happening on my setup... :-)

**Comment by hjdhjd** [comment] 2020-08-29 04:18
I don't mind the questions at all...happy to help you get up and running, but if you put yourself in my shoes for a moment and re-read the above...I spent a lot of time writing and documenting this plugin. It helps if you can directly reference the documentation you have a question about so I know that at least my effort at documenting this plugin are well-received. :smile:

How well do you understand UniFi Protect? The question you raise implies that you're fairly new to the ecosystem, is that correct?

**Comment by fpuigb** [comment] 2020-08-29 04:19
**On 2...what's the setup of Homebridge on VMware on your Dell? Specifically, how many NICs does the Dell have, and how many are configured in the VM that Homebridge runs in?**

The Dell has two NICs, I'm only using one right now. The other one it's not connected. Only one is configured in the HB VM. I just noticed that under the VM there two IPs, one IPv4 and one IPv6 even that I'm not using IPv6 in the network. I will check that. 

**On 5...you left out where this was an issue in prior releases or a new one.**

Same issue in all versions.

**Comment by hjdhjd** [comment] 2020-08-29 04:22
IP version should be fine. HomeKit primarily uses IPV4 anyway. From what you're describing, there's one path, and only one path, in and out of your VMware server when it comes to network traffic, is that correct? Meaning neither the server nor the VM are dual-homed.

**Comment by fpuigb** [comment] 2020-08-29 04:25
**I don't mind the questions at all...happy to help you get up and running, but if you put yourself in my shoes for a moment and re-read the above...I spent a lot of time writing and documenting this plugin. It helps if you can directly reference the documentation you have a question about so I know that at least my effort at documenting this plugin are well-received. 😄

How well do you understand UniFi Protect? The question you raise implies that you're fairly new to the ecosystem, is that correct?**

Not at all :-) I have been using UI since the early stages of Unifi... including Unifi Video :-) 

Ok, you probably answered my question, so when I defined (Enable.StreamOnly.Low) it basically only use the low RTSP stream?

I have to admit I'm not an expert with HB, just learning now :-)

**Comment by hjdhjd** [comment] 2020-08-29 04:28
Great! Alright then...there's nothing fancy going on with the streams. Protect defines them, we just use them. All you're telling the plugin to do is to only utilize the low stream from Protect. It's pretty straightforward. If you read the documentation on autoconfiguration, you can get a better sense of which streams get chosen when, and why.

**Comment by fpuigb** [comment] 2020-08-29 04:31
> IP version should be fine. HomeKit primarily uses IPV4 anyway. From what you're describing, there's one path, and **only one path, in and out of your VMware server when it comes to network traffic, is that correct? Meaning neither the server nor the VM are dual-homed.**

Yes only one path BUT, there are switches, UNVR and Gateway (UDMP) in the middle, so the TS it's not straight forward.

**Comment by hjdhjd** [comment] 2020-08-29 04:32
I've got a good sense of what the issue is you're running into. You've eliminated all the exotic / config-related issues. The issue is most likely latency-related, and I'll push an update in the coming days to address it. Basically, since the stream works fine locally, it's a function of not enough data getting out and back fast enough, accounting for the latency.

I'll provide an update here when I make the new version available. Appreciate you reporting it and bearing with all my questions to get to the bottom of it.

In the meantime, setting your stream quality to low should resolve it as a workaround.

**Comment by fpuigb** [comment] 2020-08-29 04:32
> Great! Alright then...there's nothing fancy going on with the streams. Protect defines them, we just use them. All you're telling the plugin to do is to only utilize the low stream from Protect. It's pretty straightforward. If you read the documentation on autoconfiguration, you can get a better sense of which streams get chosen when, and why.

Ok, I will keep testing and re-read the documentation...

**Comment by fpuigb** [comment] 2020-08-29 04:36
> I've got a good sense of what the issue is you're running into. You've eliminated all the exotic / config-related issues. The issue is most likely latency-related, and I'll push an update in the coming days to address it. Basically, since the stream works fine locally, it's a function of not enough data getting out and back fast enough, accounting for the latency.
> 
> I'll provide an update here when I make the new version available. Appreciate you reporting it and bearing with all my questions to get to the bottom of it.
> 
> In the meantime, setting your stream quality to low should resolve it as a workaround.

Thats is great! Yeah, could be latency at some point that force the ffmpeg to stop? Is the latency created by software or you think it's a network issue? I would like to know if its network issue to see how I can improve it.

Also, is there a way to include any debug option that can capture network issues?

**Comment by hjdhjd** [comment] 2020-08-29 04:38
Enjoy the read! I'll have an update this weekend in all likelihood.

I may add a debug option in the future, but it's not a high priority.

You can only improve the issue if you somehow had several billion (trillion?) dollars and can build out your own cellular network with dedicated low-latency equipment and guaranteed bandwidth. Short of that, there is nothing you can do to address the inherent latency in cellular / mobile infrastructure. :smile:

**Comment by fpuigb** [comment] 2020-08-29 04:43
> Enjoy the read! I'll have an update this weekend in all likelihood.
> 
> I may add a debug option in the future, but it's not a high priority.
> 
> You can only improve the issue if you somehow had several billion (trillion?) dollars and can build out your own cellular network with dedicated low-latency equipment and guaranteed bandwidth. Short of that, there is nothing you can do to address the inherent latency in cellular / mobile infrastructure. 😄

:-) Ok, I will go back to read the documentation and wait for your new release. Thanks for spend your time to help me with the TS... keep up the good work... 👍

**Comment by hjdhjd** [comment] 2020-08-29 04:44
Thanks, and appreciate you taking the time to bring this to my attention.

Your network setup is just fine, BTW...if it wasn't, things wouldn't work locally. :smile:

**Comment by miwagner1** [comment] 2020-08-30 18:51
I was just about to open an issue about this exact problem where everything works locally but I can only stream my logi camera which is HomeKit native but not the UniFi ones. Thank you so much for your work on this plugin.

**Comment by hjdhjd** [comment] 2020-09-04 06:42
Closing this one out. v3.6.0 is out...give it a try. Feel free to open a new issue if there are specific issues you run into. Thanks!

**Closed by hjdhjd** 2020-09-04 06:42 UTC
