### ISSUE TITLE
Start stream delay, audio, latency

### ISSUE THREAD

**Issue by tronny87** [hjdhjd/homebridge-unifi-protect2#17] opened 2020-06-07 06:27 UTC
The 3 main issues I have with this plugin: 

- the delay when you initiate a video stream (long spinning circle load time)
- a big 5-10 sec lag on the video stream itself 
- no apparent audio support (or at least if there is, no audio in my case)

Perhaps dev can look at the code for homebridge-ring and borrow an idea or two. It is super snappy, very responsive and is able to send audio and video to the Home app with about a 0.5 second delay. Also uses ffmpeg, but relies on a video stream from Ring servers. 

I'm sure since it relies on LAN devices and not a web server, this plugin can do even better!

**Comment by philipsaad** [comment] 2020-06-15 18:51
What device are you running Homebridge on? A Pi? I use the following settings, albeit not on a Pi, I have a large-ish VMWare ESXi host that is running dual Xeons, but it should should help on the Pi as well. 

I find the default ffmpeg parameters to not be to optimized for live streaming, here is my config, insert this after the _controllers_ section in the Homebridge config.

`
            "videoConfig": {
                "additionalCommandline": "-preset ultrafast -tune zerolatency -profile:v high -level 4.2 -x264-params intra-refresh=1:bframes=0",
                "maxWidth": 0,
                "maxHeight": 360,
                "audio": true
            }
`

Lowering the resolution, and switching to the ultrafast preset with zerolatency tuning seems to have the biggest impact. I'm able to get a live stream going _**with sound**_ in under 2 seconds, which cannot be beat unless the camera itself is providing a HomeKit compatible stream.

**Comment by tronny87** [comment] 2020-06-15 19:02
> What device are you running Homebridge on? A Pi? I use the following settings, albeit not on a Pi, I have a large-ish VMWare ESXi host that is running dual Xeons, but it should should help on the Pi as well.
> 
> I find the default ffmpeg parameters to not be to optimized for live streaming, here is my config, insert this after the _controllers_ section in the Homebridge config.
> 
> ```
>         "videoConfig": {
>             "additionalCommandline": "-preset ultrafast -tune zerolatency -profile:v high -level 4.2 -x264-params intra-refresh=1:bframes=0",
>             "maxWidth": 0,
>             "maxHeight": 360,
>             "audio": true
>         }
> ```
> 
> Lowering the resolution, and switching to the ultrafast preset with zerolatency tuning seems to have the biggest impact. I'm able to get a live stream going _**with sound**_ in under 2 seconds, which cannot be beat unless the camera itself is providing a HomeKit compatible stream.

Your config slightly improved latency in my stream (I still have about a 5 second lag) and fixed my missing audio, but it still takes about 10 seconds to establish the stream.

I am running the plugin on a Synology NAS.

**Comment by philipsaad** [comment] 2020-06-15 19:12
It could be that the Synology is using an underpowered CPU, which is typical for storage focused devices. Do you know if you installed ffmpeg from the Synology store or downloaded manually? It could be that it's not making use of the GPU or whatever to make use of an offloaded encode.

**Comment by tronny87** [comment] 2020-06-15 19:14
> It could be that the Synology is using an underpowered CPU, which is typical for storage focused devices. Do you know if you installed ffmpeg from the Synology store or downloaded manually? It could be that it's not making use of the GPU or whatever to make use of an offloaded encode.

ffmpeg was bundled with my install of homebridge-ring, which as I mentioned above, loads streams flawlessly and very quickly, even though they are WAN streams

**Comment by hjdhjd** [comment] 2020-06-30 17:52
@tronny87 As others have noted, audio is supported. As to the latency - I concur that I'd point this to underpowered hardware. I have no issues with latency and I've got 15+ UniFi Protect cameras streaming via homebridge simultaneously.

One thing you can try is to use a lower quality RTSP stream in Protect. Another option would be to try adding:

`"additionalCommandline": "-tune zerolatency"`

This will sacrifice quality of the stream for speed. Good luck.

Closing as these aren't bugs and this is intended behavior.

**Closed by hjdhjd** 2020-06-30 17:52 UTC

**Comment by tronny87** [comment] 2020-07-17 19:04
> @tronny87 As others have noted, audio is supported. As to the latency - I concur that I'd point this to underpowered hardware. I have no issues with latency and I've got 15+ UniFi Protect cameras streaming via homebridge simultaneously.
> 
> One thing you can try is to use a lower quality RTSP stream in Protect. Another option would be to try adding:
> 
> `"additionalCommandline": "-tune zerolatency"`
> 
> This will sacrifice quality of the stream for speed. Good luck.
> 
> Closing as these aren't bugs and this is intended behavior.

I'm not sure how an issue like this can be caused by underpowered hardware if I'm able to use another plugin (homebridge-ring) that also uses ffmpeg to fetch a video stream, and a stream over HTTP WAN nonetheless. It takes 1-2 seconds for the stream to start up inside my Home app, whereas this plugin, takes up between 6-10 seconds to start going, and with a massive delay once its going. 

I fear this may come down to the way the plugin leverages ffmpeg and you may want to look at the homebridge-ring coding to see if there's anything that can be done differently.
