### ISSUE TITLE
Connection reset happening every hour according to Homebridge log

### ISSUE THREAD

**Issue by tronny87** [hjdhjd/homebridge-unifi-protect2#38] opened 2020-08-13 14:47 UTC
Hi there, 

I was looking at my Homebridge log for the first time in quite some time and noticed some frequent activity coming from the plug-in. 

[8/13/2020, 2:15:19 PM] [UniFi Protect] X.X.X.X: Connection reset.
[8/13/2020, 2:15:19 PM] [UniFi Protect] X.X.X.X: Unable to retrieve NVR configuration information from UniFi Protect. Will retry again later.
[8/13/2020, 2:15:29 PM] [UniFi Protect] UniFi Controller [UDM-PRO]: Connected to the Protect controller API (address: X.X.X.X mac: XXXXXXXXXXX).
[8/13/2020, 2:15:29 PM] [UniFi Protect] UniFi Controller [UDM-PRO]: Connected to the UniFi realtime system events API.

This supposed connection reset seems to be happening every hour, on the hour. I was wondering whether or not this event is normal?

Thanks!

**Comment by hjdhjd** [comment] 2020-08-13 15:44
Thanks for reporting this. This is a harmless error, there for informational purposes. Connections to the controller occasionally get reset on the controller end. It’s not a bug...it’s informational.

That said, in looking at my own logs, it does seem to be occurring hourly...I’m guessing that Protect enforces a one-hour lifetime for connections. I’ll look into it and push an update to address. Thanks for raising it.

In other news...I have my G4 Doorbell...hoping to get something up and running in the coming days, depending on how busy the real world gets. :smile:

**Comment by tronny87** [comment] 2020-08-13 17:12
@hjdhjd Super stoked for doorbell support. I’ve been using the HomeKit motion alerts on the doorbell which have been working flawlessly, alongside doorbell press alerts from the Protect app.

Can’t wait to be able to get all my notifications via HomeKit and leave alerts from the Protect app behind :-)

**Comment by brianmedia** [comment] 2020-08-13 17:16
> In other news...I have my G4 Doorbell...hoping to get something up and running in the coming days, depending on how busy the real world gets. :smile:

Woohoo! 🎉 will be awesome to get the video notification on Apple TV when the doorbell rings.

**Comment by fpuigb** [comment] 2020-08-13 17:27
Can't wait to start testing the doorbell integration :-)

**Comment by hjdhjd** [comment] 2020-08-13 18:47
@fpuigb Me too! :smile:

**Comment by hjdhjd** [comment] 2020-08-13 18:47
@tronny87 I've squashed this one. It'll be in an update later. Interesting bug / quirky behavior. It was fun to chase this one.

**Comment by hjdhjd** [comment] 2020-08-16 21:00
Closing this one out - fixed in 3.2.0. There's also something there that a few folks have been waiting for...enjoy.

**Closed by hjdhjd** 2020-08-16 21:00 UTC
Labels: bug

**Comment by Laurel-Summit** [comment] 2022-08-28 02:10
@hjdhjd -- I am seeing this error numerous times in my logs: Unable to retrieve NVR configuration information from UniFi Protect. Will retry again later. and Controller API connection terminated because it was taking too long. This error can usually be safely ignored.

I am seeing these repeated many times. Is it possible this issue has returned after an update from Unifi?

**Comment by jnanes** [comment] 2022-11-09 18:33
Ditto, same for me,
